version: '3.4'

services:
  nginx:
    container_name: nginx
    build: ./docker/build/nginx
    ports:
      - 80:80
    volumes:
      - ./var/www:/usr/share/nginx/html
    depends_on:
      - php
    restart:
      always
    networks:
      default:
        ipv4_address: 172.16.1.4

  mysql:
    container_name: mysql
    build: ./docker/build/mysql
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_USER=bitrix
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=bitrix
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Europe/Moscow
    ports:
      - '3310:3310'
    networks:
      default:
        ipv4_address: 172.16.1.15
  php:
    container_name: php-fpm
    build: docker/build/php-fpm
    volumes:
      - ./var/www:/usr/share/nginx/html
      - ./docker/build/php-fpm/hosts:/etc/hosts
      - ./var/mail:/var/mail
    networks:
      default:
        ipv4_address: 172.16.1.2
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.1.0/24
